/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'userId' : Principal, 'items' : Array<CartItem> }
export interface CartEntry { 'cart' : Cart, 'principalId' : string }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface DashboardStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'lowStockAlerts' : Array<Product>,
  'totalRevenue' : bigint,
}
export type ExternalBlob = Uint8Array;
export type FragranceType = { 'fresh' : null } |
  { 'floral' : null } |
  { 'citrus' : null } |
  { 'fougere' : null } |
  { 'oriental' : null } |
  { 'gourmand' : null } |
  { 'chypre' : null } |
  { 'woody' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'priceAtPurchase' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'fragranceType' : FragranceType,
  'rating' : number,
  'image' : ExternalBlob,
  'price' : bigint,
  'reviewCount' : bigint,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'fragranceType' : FragranceType,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserEntry { 'principalId' : string, 'profile' : UserProfile }
export interface UserProfile {
  'joinDate' : Timestamp,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addReview' : ActorMethod<[ProductId, bigint, string], Review>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[], Order>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteReview' : ActorMethod<[ReviewId], undefined>,
  'deleteUserProfile' : ActorMethod<[string], undefined>,
  'getAllCarts' : ActorMethod<[], Array<CartEntry>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllUsers' : ActorMethod<[], Array<UserEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReviewsByProduct' : ActorMethod<[ProductId], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeAdminRole' : ActorMethod<[Principal], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], UserProfile>,
  'setAdminRole' : ActorMethod<[Principal], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
  'updateUserProfile' : ActorMethod<[string, string], [] | [UserProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];